// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAqKMc8Jg-75B07_QvAhIG_QKm-GTZuK8',
    appId: '1:53407187172:web:00758b5c83efe7adb32cf1',
    messagingSenderId: '53407187172',
    projectId: 'hushone-app',
    authDomain: 'hushone-app.firebaseapp.com',
    databaseURL: 'https://hushone-app-default-rtdb.firebaseio.com',
    storageBucket: 'hushone-app.appspot.com',
    measurementId: 'G-J9KVCBH2L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcFDiD_GotGnPhjCso9tHCHievk1putmQ',
    appId: '1:53407187172:android:ff873830a851797ab32cf1',
    messagingSenderId: '53407187172',
    projectId: 'hushone-app',
    databaseURL: 'https://hushone-app-default-rtdb.firebaseio.com',
    storageBucket: 'hushone-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfo5qtNDVT6edPNFl6OmQ-XE5RGZeADk4',
    appId: '1:53407187172:ios:58a0245efcffedb3b32cf1',
    messagingSenderId: '53407187172',
    projectId: 'hushone-app',
    databaseURL: 'https://hushone-app-default-rtdb.firebaseio.com',
    storageBucket: 'hushone-app.appspot.com',
    androidClientId: '53407187172-0h9ckq232jev9dd2u8re190pck2kku3o.apps.googleusercontent.com',
    iosBundleId: 'com.hushhone.hushh.hushh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfo5qtNDVT6edPNFl6OmQ-XE5RGZeADk4',
    appId: '1:53407187172:ios:58a0245efcffedb3b32cf1',
    messagingSenderId: '53407187172',
    projectId: 'hushone-app',
    databaseURL: 'https://hushone-app-default-rtdb.firebaseio.com',
    storageBucket: 'hushone-app.appspot.com',
    androidClientId: '53407187172-0h9ckq232jev9dd2u8re190pck2kku3o.apps.googleusercontent.com',
    iosBundleId: 'com.hushhone.hushh.hushh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB42aIExVEVtQFnJKxPT1tpzfeJoVEojdM',
    appId: '1:53407187172:web:1d685d84797e628bb32cf1',
    messagingSenderId: '53407187172',
    projectId: 'hushone-app',
    authDomain: 'hushone-app.firebaseapp.com',
    databaseURL: 'https://hushone-app-default-rtdb.firebaseio.com',
    storageBucket: 'hushone-app.appspot.com',
    measurementId: 'G-FH5YLMKVDH',
  );
}
